services:
  - type: web
    name: motiv-educ-ia
    env: python
    buildCommand: "pip install --only-binary=all scikit-learn numpy scipy pandas"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
